name: "Ithome Article Post Action"
author: "Charonyuu"
description: "show your latest ithome article on your github profile"

inputs:
  ghToken:
    required: true
    default: ${{ github.token }}
    description: "Your github token"
  userId:
    required: true
    default: ""
    description: "Your ithome id"
  limit:
    required: false
    default: "5"
    description: "The number of articles you want to show, limit is between 1 and 10"
  commit_message:
    description: "Commit message used while committing to the repo"
    default: "Updated with the latest ithome blog posts"
    required: false
  committer_username:
    description: "Username used while committing to the repo"
    default: "ithome-blog-upload-readme-bot"
    required: false
  committer_email:
    description: "Email id used while committing to the repo"
    default: "ithome-blog-upload-readme-bot@example.com"
    required: false
  like:
    required: false
    default: "true"
    description: "Whether to show articles with likes or not"
  comment:
    required: false
    default: "true"
    description: "Whether to show articles with comments or not"
  view:
    required: false
    default: "true"
    description: "Whether to show articles with views or not"

runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "activity"
