name: Update Readme

on:
  workflow_dispatch:

jobs:
  updateReadme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm install
      - name: Update Readme
        id: updateReadme
        uses: ./
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          userId: "20162289"
          limit: "5"
