name: Update Readme

on:
  workflow_dispatch:

jobs:
  updateReadme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm install
      - name: Update Readme
        id: updateReadme
        uses: ./
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          userId: "20162289"
          limit: "5"
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest articles" || echo "No changes to commit"
          git push