name: Update Readme

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  updateReadme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Chrome executable path
        run: |
          echo "export PUPPETEER_EXECUTABLE_PATH='/usr/bin/google-chrome'" >> $GITHUB_ENV
          npx puppeteer browsers install chrome

      - name: Update Readme with Ithome Blog
        uses: ./
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          userId: "20162289"
          limit: "5"
